In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
b = np.shape(a)
print(b)

(2, 3)


In [ ]:
#untuk mengambil elemen spesifik
print(a[0,1])

2


In [ ]:
#untuk mengambil row(r,:)
print(a[1,:3])

[4 5 6]


In [ ]:
#untuk mengambil kolom(:, c)
print(a[:1,0])

[1]


In [ ]:
a[1,1] = 10
print(a)


[[ 1  2  3]
 [ 4 10  6]]


In [ ]:
#3d array
arr3d = np.array(np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]))
print(arr3d) 
print('\n')
print(arr3d[0,1,0])
print(np.shape(arr3d))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


3
(3, 2, 2)


In [ ]:
print(np.arange(8))
print('\n')
print(np.arange(3,8))
print('\n')
print(np.arange(0,9,2))
print('\n')

[0 1 2 3 4 5 6 7]


[3 4 5 6 7]


[0 2 4 6 8]




In [ ]:
print(np.zeros(5))
print('\n')
print(np.zeros((5,5)))
print('\n')

[0. 0. 0. 0. 0.]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]




In [ ]:
#ambil elemen 3d array (r,c,h)


In [ ]:
print(np.ones(5))
print('\n')
print(np.ones((3,5)))
print('\n')

[1. 1. 1. 1. 1.]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]




In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print('Array: ')
print(a)
print('\n')

b = np.reshape(a,(4,4))

print('Array yang dimodify: ')
print(b)

Array: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


Array yang dimodify: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
TransMat = np.array(b).transpose()
print(TransMat)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
